using './main.bicep'
param Name = ''
param virtualNetworkName = ''
param remoteVnetName = ''
param remoteVnet = ''
param adminUsername = ''
param adminPassword = ''
param customData = ''
param priavteDns = ''
